### ISSUE TITLE
I set class, but he select imgs without classes to...

### ISSUE THREAD

**Issue by SvenBudak** [brandly/angular-adaptive-backgrounds#8]
I got some images, where i got no classes, i use adaptive-background ab-image-class="img" but he select every <img> tag.

**Comment by brandly** [comment]
could you provide some code to reproduce this issue?

**Comment by BamiGorengo** [comment]
<div class="icon chat" ng-class="{'default-price': user.usr_id == 0}" adaptive-background ab-image-class="round">
    <div class="btn-delete" ng-if="user.usr_id" ng-click="delete(user.usr_id)">
        <i class="fa fa-trash" aria-hidden="true"></i>
    </div>
    <img src="{{user.hasImg ? user.img : user.icon}}" alt={{user.login}}" ng-class="{'round': user.hasImg}">
</div>

Only user with Avatar get the class round. but the strange thing is, that all other boxes with default avatar (without class round) get the effect of the adaptive backgrounds script.

**Comment by brandly** [comment]
i see! so you're saying if you specify an `ab-image-class`, then you're expecting it to _only_ apply to images with that class.

it looks like [this chunk of code](https://github.com/brandly/angular-adaptive-backgrounds/blob/master/src/angular-adaptive-backgrounds.coffee#L46-L57) is to blame.

i could probably update it to say:

```coffee
if elementWithClass?
  return angular.element elementWithClass
else
  return null
```

instead of defaulting to the first image it finds. does this sound correct to you?

**Comment by BamiGorengo** [comment]
The problem is that i realy realy know only the simplest basics of javaScript. i learn now new agnularJS :P But yes, if i bind it to a class, then i want the effect only on images with this class, thats correct.

i got another error to with your script, but thats another thing...

lets do first this one thing and then the next one. you see that my english istnt so good to ;)
